main {
  Model {
    value = "MachineBufferNoSpec"
  }  // Choose from: TestUnit, CatMouse, CatMouseModular, MachineBuffer,MachineBufferNoSpec,RoboticArm,Sticks,AGV
  Solver = {
    value = "LStarPlantLearner"
  } //Choose from: frehage1,frehage2,frehage3,monolithicPlantSolver,monolithicSupSolver,modularSupSolver,LStarPlantLearner,LStarSuprLearner
}
opc {
  url = ""
  port = 4648
  runner.timeout = 300
}